# .github/labeler.yml

version: v1

labels:
  - label: 'lab1'
    sync: true
    matcher:
      title: 'Лабораторная работа №1.*'
      
  - label: 'lab2'
    sync: true
    matcher:
      title: 'Лабораторная работа №2.*'      
    
  - label: 'lab3'
    sync: true
    matcher:
      title: 'Лабораторная работа №3.*'    
  
  - label: 'lab4'
    sync: true
    matcher:
      title: 'Лабораторная работа №4.*'
  

  - label: '3824М1ПМвм'
    sync: true
    matcher:
      title: '.*3824М1ПМвм.*'

  - label: '3824М1ПМкн'
    sync: true
    matcher:
      title: '.*3824М1ПМкн.*'
      
  - label: '3824М1ПР2'
    sync: true
    matcher:
      title: '.*3824М1ПР2.*'
      
  - label: '3824М1ФИ1'
    sync: true
    matcher:
      title: '.*3824М1ФИ1.*'
    
  - label: '3824М1ФИ2'
    sync: true
    matcher:
      title: '.*3824М1ФИ2.*'
  
  - label: '3824М1сФИ1'
    sync: true
    matcher:
      title: '.*3824М1сФИ1.*'
